window.App.ActionTypes = {
    LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',
    CREATE_TODO: 'CREATE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    CHANGE_TODO: 'CHANGE_TODO',
    DELETE_TODO: 'DELETE_TODO',
};